export const seedPlants = [
  { name: 'Money Plant', price: 249, categories: ['Indoor', 'Home Decor', 'Air Purifying'], available: true },
  { name: 'Snake Plant', price: 399, categories: ['Indoor', 'Air Purifying'], available: true },
  { name: 'Areca Palm', price: 699, categories: ['Indoor', 'Air Purifying', 'Home Decor'], available: true },
  { name: 'Aloe Vera', price: 199, categories: ['Succulent', 'Air Purifying', 'Indoor'], available: true },
  { name: 'Jade Plant', price: 299, categories: ['Succulent', 'Indoor', 'Home Decor'], available: true },
  { name: 'ZZ Plant', price: 599, categories: ['Indoor', 'Low Maintenance'], available: true },
  { name: 'Rubber Plant', price: 549, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Fiddle Leaf Fig', price: 1199, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Peace Lily', price: 349, categories: ['Indoor', 'Air Purifying'], available: true },
  { name: 'Spider Plant', price: 249, categories: ['Indoor', 'Air Purifying'], available: true },
  { name: 'Pothos Golden', price: 199, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Aglaonema Red', price: 599, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Aglaonema Green', price: 499, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Syngonium Pink', price: 299, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Syngonium Green', price: 249, categories: ['Indoor'], available: true },
  { name: 'Philodendron Brasil', price: 449, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Philodendron Heartleaf', price: 399, categories: ['Indoor'], available: true },
  { name: 'Calathea Orbifolia', price: 899, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Calathea Medallion', price: 799, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Areca Palm Large', price: 1499, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Bamboo Palm', price: 699, categories: ['Indoor', 'Air Purifying'], available: true },
  { name: 'Dracaena Marginata', price: 499, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Dracaena Compacta', price: 549, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Areca Palm Table Top', price: 349, categories: ['Indoor'], available: true },
  { name: 'Croton Petra', price: 299, categories: ['Outdoor', 'Colorful Foliage'], available: true },
  { name: 'Bougainvillea Pink', price: 199, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Bougainvillea Orange', price: 199, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Hibiscus Red', price: 199, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Hibiscus Yellow', price: 199, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Jasmine Mogra', price: 249, categories: ['Outdoor', 'Fragrant', 'Flowering'], available: true },
  { name: 'Jasmine Arabian', price: 249, categories: ['Outdoor', 'Fragrant', 'Flowering'], available: true },
  { name: 'Rose Red', price: 149, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Rose Pink', price: 149, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Rose Yellow', price: 149, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Tulsi (Holy Basil)', price: 99, categories: ['Outdoor', 'Herb'], available: true },
  { name: 'Mint', price: 79, categories: ['Outdoor', 'Herb', 'Culinary'], available: true },
  { name: 'Curry Leaves', price: 129, categories: ['Outdoor', 'Herb', 'Culinary'], available: true },
  { name: 'Adenium Desert Rose', price: 699, categories: ['Outdoor', 'Succulent', 'Flowering'], available: true },
  { name: 'Echeveria Elegans', price: 299, categories: ['Succulent', 'Indoor'], available: true },
  { name: 'Haworthia', price: 249, categories: ['Succulent', 'Indoor'], available: true },
  { name: 'Gasteria', price: 249, categories: ['Succulent', 'Indoor'], available: true },
  { name: 'Kalanchoe Red', price: 349, categories: ['Succulent', 'Flowering'], available: true },
  { name: 'Kalanchoe Yellow', price: 349, categories: ['Succulent', 'Flowering'], available: true },
  { name: 'Pencil Cactus', price: 399, categories: ['Succulent', 'Outdoor'], available: true },
  { name: 'Opuntia Cactus', price: 299, categories: ['Succulent', 'Outdoor'], available: true },
  { name: 'Areca Palm XL', price: 1999, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Ficus Bonsai', price: 1499, categories: ['Indoor', 'Home Decor'], available: false },
  { name: 'Money Plant Marble Queen', price: 299, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Money Plant N’Joy', price: 299, categories: ['Indoor', 'Home Decor'], available: true },
  { name: 'Bamboo Lucky 3 Layer', price: 349, categories: ['Indoor', 'Home Decor', 'Feng Shui'], available: true },
  { name: 'Bamboo Lucky 2 Layer', price: 249, categories: ['Indoor', 'Home Decor', 'Feng Shui'], available: true },
  { name: 'Poinsettia Red', price: 399, categories: ['Indoor', 'Seasonal', 'Flowering'], available: false },
  { name: 'Chrysanthemum Yellow', price: 199, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Chrysanthemum White', price: 199, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Coleus Mix', price: 149, categories: ['Outdoor', 'Colorful Foliage'], available: true },
  { name: 'Ixora Red', price: 249, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Ixora Pink', price: 249, categories: ['Outdoor', 'Flowering'], available: true },
  { name: 'Areca Palm Dwarf', price: 499, categories: ['Indoor'], available: true },
  { name: 'Fern Boston', price: 299, categories: ['Indoor', 'Air Purifying'], available: true },
  { name: 'Fern Asparagus', price: 299, categories: ['Indoor'], available: true },
  { name: 'Dieffenbachia', price: 399, categories: ['Indoor'], available: true },
  { name: 'Anthurium Red', price: 899, categories: ['Indoor', 'Flowering'], available: true },
  { name: 'Anthurium Pink', price: 899, categories: ['Indoor', 'Flowering'], available: true },
  { name: 'Sansevieria Whale Fin', price: 1299, categories: ['Indoor', 'Succulent'], available: true },
  { name: 'Sansevieria Laurentii', price: 599, categories: ['Indoor', 'Air Purifying'], available: true },
  { name: 'Sansevieria Zeylanica', price: 549, categories: ['Indoor', 'Air Purifying'], available: true },
];
